# Generated by Django 4.1.7 on 2023-03-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
    ]
